spring.application.name=stockify

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=43200000

# Server
server.port=8081

# AWS
aws.region=${AWS_REGION:ap-south-1}
aws.ses.from-email=${AWS_SES_FROM_EMAIL}