spring.application.name=stockify

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/stockify?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=stockifyrockyrishabh9387lloydgraternoida
jwt.expiration=604800000

# Email (Brevo)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rishuchaurasia.13@gmail.com
spring.mail.password=wpmpsuxgmhxllbnk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# JWT 7 days