spring.application.name=stockify

#databse configurstion
spring.datasource.url=jdbc:mysql://localhost:3306/stockify?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rocky@123

#hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#jwt secret key
jwt.secret=stockifyrockyrishabh9387lloydgraternoida
#60 minutes
jwt.expiration=36000000  
server.port=8080    